name: Allure Report Generation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-allure-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4

      - name: Run tests 
        run: |
          mvn clean test

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always() 
        continue-on-error: true 
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure report action 
        uses: simple-elf/allure-report-action@master
        if: always() 
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
