name: Maven and REST Assured Test

on:
  workflow_dispatch: # Trigger the workflow manually
    inputs:
      tags: # Input parameter for test scenario tags
        description: "Test scenario tags"
        required: false
        default: "smoke"

jobs:
  Run-Rest-Assured-Tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run REST Assured Tests with Maven
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report

      # - name: Upload REST-Assured Allure report to GitHub
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: REST-Assured-report
      #     path: target
