name: Run Tests & Generate Report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout repo 
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: Run tests 
        run: |
          mvn clean test
          mvn allure:report
        
      - name: Get Allure reports history
        uses: actions/checkout@v4
        if: always() 
        continue-on-error: true 
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure test report 
        uses: simple-elf/allure-report-action@master
        if: always() 
        with:
          allure_results: target/allure-results
          allure_report: target/site/allure-maven-plugin
          allure_history: allure-history
          keep_reports: 20

      - name: Publish Allure test report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Post Allure test report link
        if: always()
        uses: guibranco/github-status-action-v2@main
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          target_url: https://shadynader88.github.io/transflo-api-tests/${{ github.run_number }}
